openapi: 3.0.3

info:
  title: Cosmo Tech Connector Manager API
  description: Cosmo Tech Connector Manager API
  version: 0.0.8-SNAPSHOT

servers:
  - url: 'http://localhost:8080'

tags:
  - name: book
    description: Operations about Books

paths:
  /books:
    summary: Operations about Books
    get:
      tags:
        - book
      summary: Get all the books
      responses:
        200:
          description: Success
        400:
          description: Incorrect Input
        default:
          description: Success